### ISSUE TITLE
There is code only supported by Python 3.6+, while no Python version requirement is specified

### ISSUE THREAD

**Issue by XD-DENG** [dr-leo/pandaSDMX#110]
There is line like https://github.com/dr-leo/pandaSDMX/blob/a31249da9a11e400a2b2f410d16e0010b4ff56af/pandasdmx/api.py#L145 which is using f-string and only supported by Python 3.6 and +.

However, there is no `python_requires` specified anywhere like `setup.py`.

So we need to either avoid using features like f-string which is only supported by the relatively new Python versions, or specify `python_requires` so users know they can only run the package using specific Python versions.

**Comment by XD-DENG** [comment]
Another example is https://github.com/dr-leo/pandaSDMX/blob/a31249da9a11e400a2b2f410d16e0010b4ff56af/pandasdmx/api.py#L177

**Comment by dr-leo** [comment]
Thanks for spotting. I'll add this as suggested.

Leo

**Comment by khaeru** [comment]
[Python 3.8](https://docs.python.org/3.8/whatsnew/3.8.html) and [3.7.5](https://www.python.org/downloads/release/python-375/) were recently released.
So, at the same time as we fix this, we can ensure Travis tests on the [provided versions](https://docs.travis-ci.com/user/languages/python/#python-versions) 3.6, 3.7 (latest, rather than the currently hardcoded 3.7.5), and 3.8.

**Comment by XD-DENG** [comment]
To avoid potential misunderstanding, to me what's lacking here is something like this https://github.com/pandas-dev/pandas/blob/b0f33b3f40d5742531e31aef90573b9592489592/setup.py#L822

**Comment by khaeru** [comment]
> To avoid potential misunderstanding, to me what's lacking here is something like this https://github.com/pandas-dev/pandas/blob/b0f33b3f40d5742531e31aef90573b9592489592/setup.py#L822

Yes, thank you. I'll ask for your review on #114!
