### ISSUE TITLE
Writer tests fail due to invalid csv files for expected data

### ISSUE THREAD

**Issue by dr-leo** [dr-leo/pandaSDMX#130]
Transcript:

[removed] —see attached file below: https://github.com/dr-leo/pandaSDMX/issues/130#issuecomment-596242538

**Comment by dr-leo** [comment]
The unparsable files merely contain a filename rather than csv-formatted data. These files could result from symlinks on Linux which are [by default not represented correctly on Windows](https://github.com/git-for-windows/git/wiki/Symbolic-Links).

If the above assumption is correct, a solution will require minor refactorings in the test suite.

**Comment by khaeru** [comment]
Please [format the issue description](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) using triple backticks, or else attach it as a text file, so that it's readable.

**Comment by dr-leo** [comment]
[pandasdmx_win10_test.log](https://github.com/dr-leo/pandaSDMX/files/4303761/pandasdmx_win10_test.log)
The complete pytest log is attached showing 7 failed tests.

**Comment by khaeru** [comment]
#136 resolves this by expanding `tests.data.expected_data()`. The function now handles a code-based reference—rather than filesystem symlink—to a file containing the expected data from `.to_pandas()`:
https://github.com/dr-leo/pandaSDMX/blob/4ef7e32d964e7c361f8ad4c1433e17a5a2516f42/pandasdmx/tests/data/__init__.py#L76-L92

This replaces, e.g. a symlink from ng-ts-xml.txt → ng-flat-xml.txt, so the tests should work even under Git installations on Windows where symlink support wasn't or can't be enabled.
