### ISSUE TITLE
Simplify remote.ResponseIO and make its read() method efficient

### ISSUE THREAD

**Issue by dr-leo** [dr-leo/pandaSDMX#137]
I do not see the need for the `size`arg of the `read`method. The main purpose of the wrapper should be the file echoing. However, the main problem of the read() method is its quadratic performance:

```            while size < 0 or len(self.pending) < size:
                self.pending += next(self.chunks)
```

The docs [relevantly state](https://docs.python.org/3/library/stdtypes.html):
    
    Concatenating immutable sequences always results in a new object. This means that building up a sequence by repeated concatenation will have a quadratic
runtime cost in the total sequence length. To get a linear runtime cost, you must switch to one of the alternatives below...

An alternative is using bytearray instead of bytes. Another option would be bytes.join(itertools.takewhile(...)).
 But this would require some refactoring. The current loop copies and garbage-collects a potentially very large object on each iteration.

The best option is, in my view, to delegate the read() algorithm to BytesIO by default, or an optional user-provided file. This implies reading the entire http content in the init method and write it to the file. I think this is the way to go.

**Comment by khaeru** [comment]
About performance, please re-read https://github.com/dr-leo/pandaSDMX/issues/104#issuecomment-523940222 from last August.

The code is currently designed to stream from the requests.Response object, via ResponseIO, into [lxml.etree.parse()](https://lxml.de/tutorial.html#the-parse-function) (and optionally a file). This issue and #137 propose an alternative, which is:

> reading the entire http content in the init method

Since "runtime" is mentioned, I guess that is the performance metric of concern. 

(Memory usage is probably not a metric of concern: an SDMX-ML message too large to fit in memory or on disk will not be parseable by lxml or convertable to pandasdmx.model objects, anyway.)

As a bare minimum, to evaluate whether this change is needed _or_ whether the PR achieves any change, I would suggest that you:
1. Identify a specific request that returns a very large message.
2. Use the timing tools (pointed to in that old comment) or some clear method to quantify performance of the code in `master`.
3. Explain that the performance is not acceptable. Ideally, express what is desirable/acceptable performance.
4. Quantify performance of the code in the PR, and add this information to the PR description.

**Comment by dr-leo** [comment]
Sorry. I am interested in outstanding Code quality, not in tedious justifications and byzantine processes. I am thus not interested in discussing metrics to the extent that #139 improves on every possible measure.  

Referring to the Python docs which discourage using += for its quadratic cost when concatenating immutable sequences, and observing that your algorithm has exponential (!) cost in the number of chunks, it is obvious that #139 is a no-brainer. 
 
It is easy to query datasets >>100M, e.g. from the ECB's EXR dataflow on Exchange rates, say, 100 currencies * (3000 days + 120 months + 40 quarters). A typical chunk size is 16k. ESTAT dataflows have millions of data points. I leave it up to you to do the math. 

And frankly, what's the use case proper for the Streaming model as opposed to "query once, read as you go"? Is there a Scenario in which a partial message could be parsed and rendered? If there is None, shouldn't we acknowledge that #139 improves on Code Quality and Performance and merge it? If not, why not?

 Finally, remember how much Code and documentation has been rewritten over the past 12 months without any established Need. I have no time to discuss Questions of taste (e.g. "Basic usage" vs. "Walkthrough", or "if a == 'testType': continue" vs. "if a !='textType'" and on and on and on). 

Collaboration is about team-work. This encompasses overcoming one's biases and learning from each other rather than imposing unilateral rules.

**Comment by dr-leo** [comment]
Out of curiosity rather than arguing about #139, I did a back-of-the-envolope calculation, I concluded that writing to a file has linear cost, while concatenating a str would have O(n^3) complexity. Yet, the following benchmark blew me away:


```python
from io import BytesIO

def make_chunk(l):
    return b'x' * l
    
    
def concat1(chunk, n):
    s = b''
    for i in range(n):
        s += chunk
    
    
def concat2(chunk, n):
    f = BytesIO()
    for i in range(n):
        f.write(chunk)
    '''

    Note that requests.models.ITER_CHUNK_SIZE is 512 by default, I assume the unit is bytes. Thus, 1MB = 2048 chunks. We construct 1MB  and 4MB streams with both methods.

```

In [7]: run concat_benchmark.py

In [10]: c=make_chunk(512)

In [16]: %timeit concat1(c, 2048)
71.8 ms ± 508 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [17]: %timeit concat1(c, 8192)
5.41 s ± 51.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [18]: %timeit concat2(c, 8192)
10.3 ms ± 19.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [19]:  
```
