### ISSUE TITLE
INSEE data query failing when specifying keys

### ISSUE THREAD

**Issue by Quinten-gs** [dr-leo/pandaSDMX#141]
Dear, 

I am attempting to query INSEE data using pandaSDMX 0.9 (as I unfortunately cannot install python > 3.7 and install the new version from github). The following code 

``` haxe
from pandasdmx import Request `
insee = Request('INSEE')`

code = 'BALANCE-PAIEMENTS'`

keys = {'BASIND': 'SO',
'CORRECTION': 'BRUT',
'COMPTE': 'CREDITS',
'FREQ': 'M',
'INDICATEUR': 'BALANCE_DES_PAIEMENTS',
'UNIT_MEASURE': 'EUROS',
'NATURE': 'VALEUR_ABSOLUE',
'REF_AREA': 'FE',
'INSTRUMENTS_BALANCE_PAIEMENTS': '009'}

data = insee.data(code,key=keys).write()
```

fails with the error: 
`KeyError: 'CL_PERIODICITE'`

Would this be due to an issue with how this parameter is defined in the SDMX? When I do not specify any keys for the query it does not fail. However, not all datasets are fully downloadable using no keys as the datasets are too large to query.

Many thanks for your library, it has been really helpful so far in learning about SDMX.

Best regards,
Quinten

**Comment by Quinten-gs** [comment]
UPDATE: 

In your documentation you mention for INSEE 

> An issue has been reportet apparently due to a missing pericite codelist in StructureMessages. This may cause crashes. Avoid downloading this type of message. Prepare the key as string using the web interface, and simply download a dataset.

Could you elaborate that last sentence? Do I understand correctly that we should not attempt to use the key param with pandaSDMX and go download the relevant timeseries manually?

**Comment by khaeru** [comment]
> Do I understand correctly that we should not attempt to use the key param with pandaSDMX and go download the relevant timeseries manually?

No—sorry that it's unclear.

You can use a string key, such as `key='...FOO+BAR..BAZ..'`, instead of a dict. This example queries for the values 'FOO' and 'BAR' along one dimension, and 'BAZ' along another. See the `master` branch documentation for [`Request.get()`](https://pandasdmx.readthedocs.io/en/master/api.html#pandasdmx.Request.get).

So, to paraphrase the suggestion in the docs: go to the source's web page, and use the interface to help identify a correct string. Then, copy it into your pandaSDMX code, verbatim.

> Perhaps we can contact the responsibles of INSEE to resolve this issue on their side?

Please do! It's unfortunately beyond the bandwidth that I have for this project to liaise with particular agencies and persuade them to regularize the behaviour of their services, such that there are fewer idiosyncrasies. But if you succeed in that, we can definitely update the documentation.

**Comment by dr-leo** [comment]
The Problem is that this particular codelist is missing in the message
which causes the crash when validating a key in dict form. In fact,
pandaSDMX constructs a key in string-form from a given dict when
preparing a data request. Admittedly, pandaSDMX could be more
forgiving when parsing such incomplete structure Messages.

Another Workaround alongside constructing the key in string form
manually based on the tool on the INSEE website could be to set
'references=None' when requesting the datastructure. This prevents
downloading the codelists so you can at least inspect the Dimension
order in the data structure. As a 2nd step you could request the
relevant concepts and codelists separately. This could give you a
Chance to make programmatic requests with keys. But if you only Need a
few datasets, making up a key-string as described in the previous
comment is easier.

**Comment by Quinten-gs** [comment]
Dear @khaeru and @dr-leo 

Thank you for your responses. I did not have time yet to look into this in detail but I suspect this to solve my issue. 

I filed a bug report referencing this github issue to INSEE to let them resolve this issue on their side. 

Cheers
