### ISSUE TITLE
Error when requesting series_keys for ESTAT

### ISSUE THREAD

**Issue by Quinten-gs** [dr-leo/pandaSDMX#142]
Dear, 

It is impossible to request the series_keys from most dataflows from ESTAT. Below you can find an example code

``` haxe
from pandasdmx import Request
sdmx_req = Request('ESTAT')
req = sdmx_req.series_keys('DS-016890')
```
This returns 

`AttributeError: 'DataMessage' object has no attribute 'data'`. 

I noticed that (specifically for this code DS-016890) one cannot just request the data either, once you take a look at the URL created for the data request and you request the URL you get an XML stating 
`Response too large due to client request`. This might be related. 

Best regards, 
Quinten

**Comment by dr-leo** [comment]
1. Due to my recollection, ESTAT does not support requests for series-keys-only at all. See the pandaSDMX docs for additional information on each supported data provider.
1. The standard workflow for querying partial datasets by selcting specific subsets of keys, refer to the Walkthrough section of the docs for v1.0dev or the Basic Usage section of v0.9stable. In brief: request the dataflow which, by default, gives you the codelists and datastructure as well. Export the codelist to a pandas DataFrame and decide which codes you need. Then make a data request specifying the selected keys.

**Comment by dr-leo** [comment]
This issue seems to be stale. Feel free to re-open if needed.
