### ISSUE TITLE
Help pulling ABS data

### ISSUE THREAD

**Issue by buswedg** [dr-leo/pandaSDMX#146]
The http://stat.data.abs.gov.au/ website provides an 'SDMX DATA URL' and 'SDMX Data Structure Definition URL'.

I can use the 'SDMX DATA URL' to pull the data for my desired data view. But I can't work out how to pass the DSD to decode the column codes etc. which ABS use. An example:

```
Agency_Code = 'ABS'

ABS = Request(Agency_Code)

# inventories, current prices and chain volume measures
res_id = 'QBIS/50.B+C+D+F+G+H+TOTAL.0.99.10+20+30.Q/all?'

data_response = ABS.data(resource_id=res_id)

data_response.write().unstack().reset_index()
```

I see you can pass a DSD object via:

data_response = ABS.data(resource_id=res_id, dsd=dsd)

But have tried downloading the XML via the ABS SDMX Data Structure Definition URL, and passing it as a string to dsd. And that hasn't worked.

Ideas/ help?

**Comment by buswedg** [comment]
FYI, here is an example SDMX DATA URL:

http://stat.data.abs.gov.au/restsdmx/sdmx.ashx/GetData/QBIS/50+70.B+C+D+F+G+H+TOTAL.0.99.10+20+30.Q/all?startTime=2017-Q1&endTime=2019-Q4

And corresponding SDMX Data Structure Definition URL:

http://stat.data.abs.gov.au/restsdmx/sdmx.ashx/GetDataStructure/QBIS

**Comment by dr-leo** [comment]
Hi,

thanks for the thorough Research on ABS.

Regarding ABS, pandaSDMX only supports data Messages. Reason: when I implemented support for ABS, its REST API supported SDMXML 2.0 and SDMXJSON 2.1. pandaSDMX only implements SDMX 2.1. So XML Messages from ABS cannot be processed. And the JSON flavor of SDMX 2.1 was in the making, ie. structure Messages were not yet part of the Standard. This has changed in the meantime. We'd have to check if ABS supports SDMXJSON structure Messages and add support in pandaSDMX. This would indeed be a must-have, I think. but this would take a few months.

As a quick fix, you can extract human-readable Code descriptions from the SDMXJSON data Messages in About 10 lines of Code. 

pandaSDMX does not support this as it is at odds with the Standard, Tongue-in-cheak: descriptions have been aded to the JSON data message Formate precisely because JSON structure Messages were not available when the data message Format was published.

I will look at your links asap though to understand the state of implementation at ABS.

**Comment by buswedg** [comment]
Ok no worries. In that case, I'll just do something like this for now:

```
for i, col in enumerate(df.columns):
    
    if col not in ['Time Period', 0]:
        
        dic_val = {}

        ls_codes = dsd['message:Structure']['message:CodeLists']['CodeList'][i]['Code']
        ls_codes = [ls_codes] if len(ls_codes) <= 2 else ls_codes
        
        for code in ls_codes:
            #print(code['@value'], code['Description'][0]['#text'])
            dic_val[code['@value']] = code['Description'][0]['#text']
                
        df = df.replace({col: dic_val})
```

**Comment by dr-leo** [comment]
Great, if this works for you.

Btw: The links to data and datastructure messages in XML conform to SDMX 2.0 as you can see from the schema
URL. pandaSDMX does not support this. Rather, the data messages you get are 
in JSON format. These contain human-readable descriptions of the relevant codes (rather than the full codelists). However, if performance is not an issue you may well hack the SDMXML 2.0 datastructure msg.
