### ISSUE TITLE
Fix or explain tests/data/cache

### ISSUE THREAD

**Issue by dr-leo** [dr-leo/pandaSDMX#152]
Having pulled the latest changes from master, and running the tests without remote-data, the repo contains 63 new, uncommitted files in test/data/cache (as distinct from pandasdmx/tests/data). The 63 files in tests/data/cache add up to 256 MB. 

What's going on here?

**Comment by khaeru** [comment]
As the directory name indicates, this is a 'cache' for 'test' 'data'.

When doing the --remote-data tests, the network access can be a slow step, so the (already existing) requests-cache feature is used within the test suite to cache the return values. This saved a lot of time in developing the full IM implementation, and also let me inspect the cached version of the server's response to see the different variants of SDMX-ML messages.

Some other points/implications:
- The 'tests/' directory is moved to 'pandasdmx/tests/', the standard location. This means that .gitignore now excludes 'pandasdmx/tests/data/cache' (the current location), but doesn't mention 'tests/data/cache/' (the old location). So you're seeing the cache created while running the old tests.
- Because it's a cache, it can be safely deleted at any time.
- Because it's not in the repository, there is no cache when the Travis CI builds begin, and so the daily 'cron' build always fetches fresh data from the remote source.
- Because this is only within the test suite, no cache is created for normal usage in user code *unless* the user asks for it.

I hope this clarifies!
- If reading the code was not sufficient to reveal this, we can add comments/docstrings within the test suite to make it clear.
- Please close the issue if the question is answered.

**Comment by dr-leo** [comment]
To follow up:

1. Shouldn't the Cache live in the new Location, i.e. pandasdmx/Tests/data/Cache rather than Tests/data/Cache?
1. gitignore should be adapted to ignore the Cache wherever it sits.

**Comment by khaeru** [comment]
> 1. Shouldn't the Cache live in the new Location, i.e. pandasdmx/Tests/data/Cache rather than Tests/data/Cache?

Yes, it does. The key part of my last comment was the phrase: "So you're seeing the cache **created while running the old tests**."

The path that is used (now and in the future) is relative to the current tests location: https://github.com/dr-leo/pandaSDMX/blob/c578985ac97ab358c3866de0763e2db6b580c327/pandasdmx/tests/test_sources.py#L105-L111

I realize I made a typo above, so the directory is 'pandasdmx/tests/data/**.cache**', with the leading dot…

> 2. gitignore should be adapted to ignore the Cache wherever it sits.

…so it is ignored by this line in .gitignore: https://github.com/dr-leo/pandaSDMX/blob/c578985ac97ab358c3866de0763e2db6b580c327/.gitignore#L4

The top-level 'tests' directory no longer exists, nothing uses it, and nothing will be created there. You can safely delete it entirely and it will not be recreated.

**Comment by dr-leo** [comment]
I forgot to Mention that I run the test Suite issuing one of the
following commands:
* `pytest`
* `pytest --remote-data`

Based on your last bullet Point, the Cache should not have been
created on my box in the first place.

I even don't know off Hand how to instruct the test Suite to Cache
remote Responses. So there might be another reason for populating the
Cache.

Rethinking package layout, I agree it is better to store the Cache at
top Level rather than within the test Suite. But I think there should
be a single dir, not three nested Levels. At least this should be
documented for 1.0.0.

**Comment by khaeru** [comment]
>  Based on your last bullet Point, the Cache should not have been created on my box in the first place.

That's not what I meant by:

> Because this is only within the test suite, no cache is created for normal usage in user code unless the user asks for it.

To reiterate and explain in more detail:
1. Running the data source tests (with --remote-data) *always* creates a cache. The code I linked to at https://github.com/dr-leo/pandaSDMX/issues/152#issuecomment-609655660 is *always* run for these tests, because it is part of a fixture used by these tests. So it was created when you ran the tests previously.

2. For an **ordinary** user of pandaSDMX, who only installs the package to use it and **does not choose to run the tests** ("normal usage in user code"), no cache is created. The user must:
   - install requests-cache, and
   - explicitly give the arguments when creating their Request object.

   In this case, they can put the cache wherever they want, or wherever requests-cache defaults. pandaSDMX never overrode or pre-empted this, so there's no change in behaviour.

Per (1), we don't have developer guidelines or documentation yet, but I'd be happy to add some after 1.0 is release. I've aimed to make the code readable for anyone who has the pytest documentation.

**Comment by dr-leo** [comment]
Got it.

Assuming that requests-cache stores files automatically in Tests/data/Cache rather than pandasdmx/Tests/data/Cache, I would still add the Location to gitignore.

However, that assumption seems not very plausible. 

Never mind. I'll Change gitignore and commit to master. If you Need a PR, feel free.
