### ISSUE TITLE
Benchmarking v1.0.0 against v0.9

### ISSUE THREAD

**Issue by dr-leo** [dr-leo/pandaSDMX#162]
Out of curiosity I ran a dead-simple benchmark which loads a pre-fetched list of dataflows from estat:

```python
flows = Request('estat').dataflow(tofile='estat_flows.xml')
```

The file sizte is about 4.1MB.

Benchmark results:

```# v1.0.0dev
In [34]: %timeit data_resp=sdmx.read_sdmx('estat_flows.xml')
4.13 s ± 21.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [35]: exit

(sdmx37) C:\Users\a3305\documents\github>
(sdmx37) C:\Users\a3305\documents\github>deactivate
DeprecationWarning: 'deactivate' is deprecated. Use 'conda deactivate'.

(sdmx37) C:\Users\a3305\documents\github>conda.bat deactivate

(base) C:\Users\a3305\documents\github>
(base) C:\Users\a3305\documents\github>activate pandasdmx09

(pandasdmx09) C:\Users\a3305\documents\github>ipython
Python 3.8.1 (default, Jan  8 2020, 15:55:49) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.11.1 -- An enhanced Interactive Python. Type '?' for help.

# v0.9:
In [1]: import pandasdmx as sdmx

In [4]: estat=sdmx.Request('estat')

In [5]: flows=estat.get(fromfile='estat_flows.xml')

In [6]: %timeit flows=estat.get(fromfile='estat_flows.xml')
122 ms ± 902 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [7]:  
```

 So v0.9 is about 34 times faster than v1.0dev when parsing a 4MB structure message.

Sure, v1.0 has quite a few advantages. Still, the performance gap is significant. 

I wonder if v1.0 would be faster when skipping pydantic validation by default using .construct().

Other proposals to make v1.0 faster are welcome.

**Comment by khaeru** [comment]
Excellent, thanks for taking this step into benchmarking the code.

> I wonder if v1.0 would be faster when skipping pydantic validation by default using .construct().

That's an interesting suggestion. There could be a flag like `API_MODE` or something like that:
- For ordinary use, leave it **off** as suggested.
- For development purposes, e.g. running the test suite, turn it **on**.
  - This helps (a lot!) to identify coding errors in the message readers, the main purpose for which it was used in the first place.
  - Could also show users how to turn it on, in order to debug when they are encountering errors.

Two things that would need investigation (thus time):
1. How extensive the code changes would be to enable this switch. Objects are instantiated in many places.
2. Whether the reader code *relies* on pydantic's type checking. For example if there's code like:
   ```
   try:
       obj.attr = value
   except Exception:
       # pydantic itself has raised an Exception because *value* was the wrong type
       obj.attr = some_other_value
   ```

   The code *should not* rely on this, and I do avoid writing code this way out of habit. But it still requires a thorough check.

I'll gladly do these for a 1.1 follow-up release, but don't expect I can find time to do them before 1.0.

**Comment by dr-leo** [comment]
Can be discussed in #144
