### ISSUE TITLE
IMF DSD ECOFIN_DSD: TIME_FORMAT shows up as attribute and dimension

### ISSUE THREAD

**Issue by dr-leo** [dr-leo/pandaSDMX#171]
'''
msg=sdmx.read_sdmx('ECOFIN_DSD.xml')
dsd=msg.structure.ECOFIN_DSD
[(d.id, d.order) for d in dsd.dimensions]
[('DATA_DOMAIN', 1),
 ('REF_AREA', 2),
 ('INDICATOR', 3),
 ('COUNTERPART_AREA', 4),
 ('FREQ', 5),
 ('TIME_PERIOD', 6),
 ('TIME_FORMAT', 1)]

'''

TIME_FORMAT should only occur as attribute. The bug seems to surface only when the DSD is retrieved with defaulted references param, i.e. 'msg=imf.datastructure('ECOFIN_DSD')`

**Comment by dr-leo** [comment]
For clarification: TIME_FORMAT should only be rendered as attribute. The dimensions extracted with LXML.etree are as follows:

```In [25]: [d.attrib for d in dim]
Out[25]:
[{'urn': 'urn:sdmx:org.sdmx.infomodel.datastructure.Dimension=IMF:ECOFIN_DSD(1.0).DATA_DOMAIN', 'id': 'DATA_DOMAIN', 'position': '1'},
 {'urn': 'urn:sdmx:org.sdmx.infomodel.datastructure.Dimension=IMF:ECOFIN_DSD(1.0).REF_AREA', 'id': 'REF_AREA', 'position': '2'},
 {'urn': 'urn:sdmx:org.sdmx.infomodel.datastructure.Dimension=IMF:ECOFIN_DSD(1.0).INDICATOR', 'id': 'INDICATOR', 'position': '3'},
 {'urn': 'urn:sdmx:org.sdmx.infomodel.datastructure.Dimension=IMF:ECOFIN_DSD(1.0).COUNTERPART_AREA', 'id': 'COUNTERPART_AREA', 'position': '4'},
 {'urn': 'urn:sdmx:org.sdmx.infomodel.datastructure.Dimension=IMF:ECOFIN_DSD(1.0).FREQ', 'id': 'FREQ', 'position': '5'},
 {'urn': 'urn:sdmx:org.sdmx.infomodel.datastructure.TimeDimension=IMF:ECOFIN_DSD(1.0).TIME_PERIOD', 'id': 'TIME_PERIOD', 'position': '6'}]


```

**Comment by khaeru** [comment]
This is an error in the data returned by the IMF source. The data:
```python
import pandasdmx as sdmx
sdmx.Request('IMF').datastructure('ECOFIN_DSD', tofile='debug.xml')
```

```sh
$ xmllint --format debug.xml >debug-format.xml
```
contains a definition for a `<str:Attribute id="TIME_FORMAT">` but no Dimension with that ID.

Later, in the constraints for specific data flows, it includes both:
```xml
      <str:ContentConstraint urn="urn:sdmx:org.sdmx.infomodel.registry.ContentConstraint=IMF:01R_CONSTRAINT(1.0)" isExternalReference="false" agencyID="IMF" id="01R_CONSTRAINT" isFinal="false" type="Allowed" version="1.0">
        <com:Name xml:lang="en">01R_CONSTRAINT</com:Name>
        <str:ConstraintAttachment>
          <str:Dataflow>
            <Ref package="datastructure" agencyID="IMF" id="01R" version="1.0" class="Dataflow"/>
          </str:Dataflow>
        </str:ConstraintAttachment>
        <str:CubeRegion include="true">
          ...
          <com:KeyValue id="TIME_FORMAT">
            <com:Value>PT1M</com:Value>
            <com:Value>P6M</com:Value>
            <com:Value>P3M</com:Value>
            <com:Value>P1M</com:Value>
            <com:Value>P1Y</com:Value>
            <com:Value>P7D</com:Value>
            <com:Value>P1D</com:Value>
          </com:KeyValue>
        </str:CubeRegion>
      </str:ContentConstraint>
```
and
```xml
      <str:ContentConstraint urn="urn:sdmx:org.sdmx.infomodel.registry.ContentConstraint=IMF:CBS_CONSTRAINT(1.0)" isExternalReference="false" agencyID="IMF" id="CBS_CONSTRAINT" isFinal="false" type="Allowed" version="1.0">
        <com:Name xml:lang="en">CBS_CONSTRAINT</com:Name>
        <str:ConstraintAttachment>
          <str:Dataflow>
            <Ref package="datastructure" agencyID="IMF" id="CBS" version="1.0" class="Dataflow"/>
          </str:Dataflow>
        </str:ConstraintAttachment>
        <str:CubeRegion include="true">
          ...
          <com:Attribute id="TIME_FORMAT">
            <com:Value>P6M</com:Value>
            <com:Value>P1Y</com:Value>
            <com:Value>P3M</com:Value>
            <com:Value>P1M</com:Value>
          </com:Attribute>
        </str:CubeRegion>
      </str:ContentConstraint>
```

Note the difference between `<com:KeyValue>` and `<com:Attribute>`. The XML schema—in particular, SDMXCommon.xsd—shows:
```xml
<xs:complexType name="CubeRegionType">
  <xs:annotation>
    <xs:documentation>CubeRegionType defines the structure of a data cube region. This is based on the abstract RegionType and simply refines the key and attribute values to conform with what is applicable for dimensions and attributes, respectively. See the documentation of the base type for more details on how a region is defined.</xs:documentation>
  </xs:annotation>
  <xs:complexContent>
    <xs:restriction base="RegionType">
      <xs:sequence>
        <xs:element name="KeyValue" type="CubeRegionKeyType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="Attribute" type="AttributeValueSetType" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:restriction>
  </xs:complexContent>
</xs:complexType>
```
and later:

> CubeRegionKeyType is a type for providing a set of values **for a dimension** for the purpose of defining a data cube region.

> AttributeValueSetType defines the structure for providing values **for a data attribute**.

At a rough count, `<com:Attribute id="TIME_FORMAT">` (the correct usage) occurs 19 times, and `<com:KeyValue id="TIME_FORMAT">` (the incorrect usage) occurs 39 times.

**Comment by khaeru** [comment]
For this specific content, namely:
- `<com:KeyValue>` is used with a specific ID.
- The DSD (if one is in the message or supplied by the user) does not have a Dimension with this ID.
- The DSD (if one in the message or supplied by the user) has an Attribute with the same ID.

…I can imagine at least three behaviours:
1. Interpret the `<com:KeyValue>` as specified in the standard—referring to a Dimension object, although one that may not be explicitly defined in the current message.
2. Interpret the situation as an error and refuse to parse the message.
3. Interpret the situation as this particular IMF mistake and cover for it, i.e. use the Attribute even though the XML element unambiguously indicates a Dimension.

(1) is the current behaviour. This is essential to parsing any message where the DSD is not included or supplied by the user, e.g. many DataMessages: a Dimension object must be created for every dimension that is referred to by KeyValue XML elements; a DataAttribute object for every attribute referred to by Attribute XML elements, etc.

I assume, due to the fixation on this particular DSD, that (2) is undesirable.

(3) is the start of a very slippery slope of introducing workarounds and special treatment for non-IM content. One workaround becomes the excuse for a second and third, and then the possibilities for them to interact in weird ways (and produce behaviour that's unintelligible to the user) multiplies geometrically. I, at least, have no time whatsoever for maintaining that kind of code.

**Comment by dr-leo** [comment]
Your interpretation ignores how the chapter on Content constraints in the technical notes (Part 6 of the SDMX Standard?) specifies the cascade of constraints attachable at each of the three Levels (DSD, Dataflow and ProvisionAgreement). It is stated therein that a constraint must not be interpreted so as to extend the set of codes allowed at the higher Levels. The Absence of a TIME_FORMAT Dimension in the DSD thus dictates what I consider as the only reasonable behavior: ignore any KeyValue of a CubeRegion not matchd by any constrainable Dimension defined by the DSD. The same would obviously  hold true if a DSD-Level constraint yielded a codeset <= the one defined by a lower-level constraint, say, at Dataflow-level. The latter would not Change a bit notwithstanding that it would in the Absence of a more restrictive DSD-level constraint.

I am puzzled by how you describe the construction of the KeyValue from a dataset absent the DSD. In v0.9 I construct the ordered set of Dimension IDs from some SeriesKey, i.e. the KeyValues which are descendents of a SeriesKey  node rather than the set of all keyValues found somewhere in the dataset.

Summing up, I do not see any error in that StructureMessage from the IMF merely because the KeyValue for TIME_FORMAT is redundant in this particular context. In a different context, i.e. applied to a DSD, or Dataflow structured by it, which happens to define a TIME_FORMAT Dimension, it makes perfect sense (notwithstanding that the com:Attribute of the same ID would then be regarded as redundant). I assume that the sets of Dimension IDs and Attribute IDs must be disjoint although this is not explicitly stated anywhere. But otherwise, structure-specific datasets would be ambiguous. Part of the Beauty of SDMX is the reusability of artefacts. The lax usage of TIME_FORMAT in the constraint you Quote is the consequence of that reusability.

The above understanding is compatible with the Schema you Quote.

  The current behavior is untenable also because it results in two dimensions with order 1 (wherever the order Attribute of TIME_FORMAT "Dimension" Comes from). 

Finally, we may merely see the tip of the iceberg here. The "fixation" on this particular DSD is simply due to my time constraints.

**Comment by dr-leo** [comment]
To add:

If the DSD did not define a TIME_FORMAT Attribute in its AttributeDescriptor either, the same constraint being attached to the dataflow, you wouldn't even know the codelist representing These ficticious components. OK, you might still settle for the codes included in the constraint. But what if the constraint is excluding, i.e. subtracting some codes from the codelist referenced by the Dimension or Attribute through their Concept-identities?

 The current algorithm seems to be partially flawed. Dimensions and Attributes are simply to be constructed from "members" of the respective descriptors, that's it.

**Comment by khaeru** [comment]
> ignore any KeyValue of a CubeRegion not matchd by any constrainable Dimension defined by the DSD

Let's call this idea behaviour (4). It seems like a reasonable approach. It would require changing `.get(...)` here to item indexing `[...]`: https://github.com/dr-leo/pandaSDMX/blob/3d2507d6232132eb2313b0eba6f4e3c2423f742e/pandasdmx/reader/sdmxml.py#L1283-L1285

This will raise KeyError when the component (dimension or attribute) is missing, which must then be handled. What should the code do when if it chooses to ignore elements of a message? Log a warning?

> I am puzzled by how you describe the construction of the KeyValue from a dataset absent the DSD. In v0.9 I construct the ordered set of Dimension IDs from some SeriesKey, i.e. the KeyValues which are descendents of a SeriesKey node rather than the set of all keyValues found somewhere in the dataset.

These are the same thing. A DataSet only has one DimensionDescriptor; "all KeyValues found somewhere in the dataset" must appear in it.

> I do not see any error in that StructureMessage from the IMF merely because the KeyValue for TIME_FORMAT is redundant in this particular context. In a different context, i.e. applied to a DSD, or Dataflow structured by it, which happens to define a TIME_FORMAT Dimension, it makes perfect sense (notwithstanding that the com:Attribute of the same ID would then be regarded as redundant).

The XML snippets are constraints for particular dataflows, e.g. `01R` in the first example; read the `<str:ConstraintAttachment>` tag. These dataflows are defined (elsewhere in the same message) as being structured by `ECOFIN_DSD`:
```xml
      <str:Dataflow urn="urn:sdmx:org.sdmx.infomodel.datastructure.Dataflow=IMF:01R(1.0)" isExternalReference="false" agencyID="IMF" id="01R" isFinal="false" version="1.0">
        <com:Name xml:lang="en">Exchange Rates and International Reserves (01R) for Collection</com:Name>
        <com:Description xml:lang="en">Exchange Rates and International Reserves (01R) for Collection</com:Description>
        <str:Structure>
          <Ref package="datastructure" agencyID="IMF" id="ECOFIN_DSD" version="1.0" class="DataStructure"/>
        </str:Structure>
      </str:Dataflow>
```
All three of these objects—`01R_CONSTRAINT`, `01R`, and `ECOFIN_DSD`—have URNs, meaning that the definitions in this message are complete, final, and globally unique.

So there's a few possibilities:
- IMF (or someone else) has a DSD (other than `ECOFIN_DSD`) that has a TIME_FORMAT Dimension, and a dataflow structured by it (other than `01R`) that refers to `01R_CONSTRAINT`. This other dataflow is *not* included in the `<str:ConstraintAttachment>` of `01R_CONSTRAINT`, yet IMF *does* maintain the otherwise-useless KeyValues for usage in this other dataflow and other DSD.
- IMF has plans to someday issue new versions of `01R` and/or `ECOFIN_DSD` to add a TIME_FORMAT Dimension without revising `01R_CONSTRAINT`.
- It's an error; IMF *meant* to constrain the TIME_FORMAT Attribute.

I guess one can't know without asking, but in my view Ockham's razor applies.

> I assume that the sets of Dimension IDs and Attribute IDs must be disjoint although this is not explicitly stated anywhere. But otherwise, structure-specific datasets would be ambiguous.

The standards don't oblige anyone to produce or convey structure-specific XML. What you seem to have identified is a binary choice that data providers must make for each DSD: either have disjoint component IDs, or be unable to produce structure-specific XML.

> The "fixation" on this particular DSD is simply due to my time constraints.

That's understandable! But, in your view, how many/which other particular queries will need the same amount of attention before #145 can be addressed?

**Comment by dr-leo** [comment]
Does Ockham's Razor apply?

I couldn't care less. It is not our Job to second-guess the IMF's
reasons for providing redundant, if confusing, stuff in its Messages,
or worse, to contrive algorithms to exhaust all artefacts within an
SDMX message. We get lots of unused codes in codelists, validate keys
in the elusive hope that there will be data for some data Point etc.
Our self-inflicted task is simply to implement an SDMX 2.1-compliant
Client. And this means we must not invent components out of the blue
only to Prevent some constraint from being what it is: useless
according to the rules of the standard.

I don't know why such exception is raised. I thought a constraint is
attached to a DSD, Dataflow or ProvisionAgreement. Here, each
constraint is attached to some ConstrainableArtefact, whether or not
there is something to constrain.

In v0.9, the source of all my biases, I have implemented the cascading
algorithm for constraints as a method of the message class. I still
believe this is the best place, except Maybe outside any class. It
starts from the dimensions described by the DSD structuring the
present dataflow, takes the codelists as startingpoints, converts them
to sets for Efficiency, so I work with Hashes of strings rather than
Code instances. I check if there are constraints attached to the DSD,
Strip off any codes from the codesets as specified by the relevant
constraints, do the same for constraints attached to the Dataflow and
in Theory, provisionagreements. - As a pragmatic, though not
standard-compliant decision, I disregarded constraints on Attributes
as those are merely useful to dataset providers, while v0.9 only wants
to be a tool for data consumers.

I assume you know all that. therefore, I wonder how a constraint in
v1.0dev can be incomplete or lacking some key merely because the
dataflow or DSD it is attached to does not mirror all the keyvalues or
Attribute IDs present in the constraint.

A constraint is a self-contained artefact. It can live without being
useful. If the artefact it is attached to is not present in the
current message, query it! - I think SDMX even supports requests for
bare constraints much like a datastructure may reference a ton of
concepts/codelists not present in the message just because the
references param was set to None.

**Comment by khaeru** [comment]
There are a couple recurring tangents here that we don't need to discuss:

One is **use or application** of ContentConstraints.
- The Reader, as the name implies, reads XML and produces the SDMX-IM Python objects they represent. That's it. ContentConstraints may contain MemberValues, which are unrelated to Codes.
- The use of a ContentConstraint in combination with other objects only happens if and when it is needed. Only at this point, and only if there is a MemberSelection for a Component that has a local representation enumerated by a CodeList, does the relationship between MemberValues and Codes become relevant.

> A constraint is a self-contained artefact. It can live without being useful. If the artefact it is attached to is not present in the current message, query it!

This also isn't relevant here. As I said above (https://github.com/dr-leo/pandaSDMX/issues/171#issuecomment-617788501), Constraint `01R_CONSTRAINT` is in the message. It is attached to data flow `01R` *only*, which is **also in the message**. That data flow is in turn structured by `ECOFIN_DSD`.

So about the actual issue and solution:

> > [B]ehaviour (4) […] seems like a reasonable approach. It would require changing `.get(...)` here to item indexing [...]: https://github.com/dr-leo/pandaSDMX/blob/3d2507d6232132eb2313b0eba6f4e3c2423f742e/pandasdmx/reader/sdmxml.py#L1283-L1285
> > This will raise KeyError when the component (dimension or attribute) is missing…
>
> I don't know why such exception is raised. I thought a constraint is attached to a DSD, Dataflow or ProvisionAgreement. Here, each constraint is attached to some ConstrainableArtefact, whether or not there is something to constrain.

To explain this single line of code and the suggested change to `getattr(dsd, kind[0])[elem.attrib('id')]`:

- `getattr(dsd, kind[0])`:
  - [getattr()](https://docs.python.org/3/library/functions.html#getattr) is a Python built-in method.
  - `dsd` is the DSD that the ContentConstraint is attached to. In the case we are discussing, this object exists in the current message, and we have a reference to it.
  - `kind[0]` is either the string 'attributes' or 'dimensions'.
  - So this fragment is equivalent to `dsd.attributes` (i.e. the AttributeDescriptor) or `dsd.dimensions` (DimensionDescriptor). A DSD instance always has these objects, though they may be empty.
- `[elem.attrib('id')]`:
   - `elem.attrib('id')` is the XML id attribute of the <com:KeyValue> or <com:Attribute> tag.
   - `[ ]` is element lookup. In ComponentList (the parent of AttributeDescriptor and DimensionDescriptor), this is provided as a convenience to look up a specific component, which are stored in the `.components` attribute.
- So overall this suggested code, *in the example under discussion*, is equivalent to:
  ```python
  dsd.attributes.components['TIME_FORMAT']
  ```
- I hope you understand why this will raise KeyError. Remember, `01R_CONSTRAINT` can be linked through `01R` to `ECOFIN_DSD`—that's not the issue. It's that `ECOFIN_DSD` lacks an Attribute of this name 'TIME_FORMAT'.

This is why I went on to say:

> This will raise KeyError when the component (dimension or attribute) is missing, *which must then be handled.* What should the code do when if it chooses to ignore elements of a message? Log a warning?

The basic programming principle here is: **avoid silent failure to handle input; this is confusing to the user.** I think a reasonable behaviour would be something like:
```python
log.warning("'ECOFIN_DSD' has no Attribute 'TIME_FORMAT', wanted by <ContentConstraint: 01R_CONSTRAINT>.data_content_region -- 7 keys ignored')
```

Even if you don't want to write this, I still need your answer before writing anything, in order to avoid offending other preferences and rehashing this issue.

**Comment by dr-leo** [comment]
Thanks for the explanation. I agree with your proposal to raise a warning in case a key or attribute mentioned by a constraint is not mirrored by the DSD. I have no strong feelings how such warning should be recorded. I think by default it should merely be logged, but I happily leave it up to you. The main benefit is that IMF dataflows will hopefully be processed without hiccups so #119 can be closed.
