### ISSUE TITLE
Read structural data from a file

### ISSUE THREAD

**Issue by HubertBIS** [dr-leo/pandaSDMX#179]
Hi,

In version 0.9 you could read a SDMX structural file instead of having to get it from the web service
    req = sdmx.Request('')
    msg = req.codelist(fromfile=filename)

This has disappeared with version 1.0.1. Is there still the option to load structural data using files?

Thanks,
Hubert

**Comment by dr-leo** [comment]
Hi,

sorry for this backwards incompat.

Now there is the `pandasdmx.read_sdmx()` function. It is defined in
`pandasdmx.api.py`. Please let me know if this doesn't work for you.

Rgds, Leo

**Comment by HubertBIS** [comment]
Hi,

Thanks for the quick answer. Yes read_sdmx() works fine, however the result of the conversion to pandas (previously write()) is also quite different.
Moreover the content of the Type column seems a bit strange:
    resp = sdmx.read_sdmx(dsdfile,format = 'XML')
    df = sdmx.to_pandas(resp.codelist)

![image](https://user-images.githubusercontent.com/67063301/84922396-13c65680-b0c6-11ea-9524-bfde0d3e8a6a.png)

Rgds, Hubert

**Comment by dr-leo** [comment]
Hubert,

your feedback is much appreciated.

Apologies. Due to my blindness screenshots are of Little use to me. So
plain text would help me understand the Problem.

Granted that the shift from v0.9 to v1.0 has brought About some
oddities alongside a number of, I think, important improvements some
of which are more visible to the user than others.

v1.0 is essentially an almost complete rewrite by a former
collaborator who initially wanted to add one feature but ended up in
re-inventing lots of wheels. We split over mounting disagreements.
See, e.g., #145. A related Problem is my limited dev time thanks to
two Kids. Moreover, I have a new pet Project: an SDMX Driver for
[intake](https://intake.readthedocs.io). If you work at the BIS as
your GH Name suggests, you might be interested.

I'll do my best to fix the issue once understood. Or, even better, if
you find the time, do a PR. The writer module is fairly clean and
reasonably well-designed, so it should not be too hard.

Leo

**Comment by dr-leo** [comment]
v1.1.0 has just been released. Code-breaking changes compared to v0.9 persist for better or worse. Those relating to the pandas writer are intended, others could perhaps be mitigated if I had more dev time or others contributed code.
