### ISSUE TITLE
Parse and query a DSD

### ISSUE THREAD

**Issue by brockfanning** [dr-leo/pandaSDMX#181]
I don't think this is the intended usage of the library, but I was wondering if it might be possible to use PandaSDMX to parse and query a DSD, given a remote URL or local file. For example, I am interested in things like:
* Getting a list of all the codelists in a DSD
* Getting a list of all the dimensions in a DSD
* Getting a dimension by its ID
* etc.

I had a quick look at the DataStructureDefinition code, but nothing jumped out at me. Thank you!

**Comment by dr-leo** [comment]
Hi,

pandaSDMX provides These Features since 2015. It is best practice to
query a specific DataflowDefinition. By Default, the Response will
include the DatastructureDefinition referenced by that dataflow which,
in turn, references the codelists describing the dimensions. The
codelists and related concepts are contained in such Response as well
alongside other Information such as DataProvider, constraints to be
applied to codelists in the context of the selected dataflow.

This is extensively documented at

https://pandasdmx.readthedocs.io/

under "Walkthrough", or shown at a glance in the 10-lines Code example.

It is straightforward to browse dimensions and codelists at model
Level alongside any exported Pandas Series or Dataframes. to this end,
once you've queried a StructureMessage as shown in the 10 lines
example, do something like:

>>> metadata.structure

Then Focus on the DataStructureDefinition by ist ID (= the only key in
the DictLike), and look at the `dimensions`and `attributes` attribute.
Note that each enumerated Dimension and Attribute (in the SDMX sense)
has a `local_representation` Attribute whose ènum`  attfibute Shows
the codelist at model Level. Other dimensions, in particular, the
MeasureDimension is likely to be of a non-enum type such as float.

Please let me know whether this has gotten you started or whether you
Need any additional Information.

Leo

**Comment by brockfanning** [comment]
Thanks very much @dr-leo. Apologies for my SDMX ignorance, but is it possible to query a DataflowDefinition with only a URL to a DSD? (I have not fully grasped the idea of a dataflow, probably).

The reason I bring this up is that I'm working on a tool that needs to create a drop-down listing all the dimensions in a DSD, and additional drop-downs for each associated code.

Thanks again for the feedback.

**Comment by dr-leo** [comment]
v1.1.0 has been released. Re-open this in case there is anything to fix or explain.
