### ISSUE TITLE
Create file for UNICEF to be listed as default provider. 

### ISSUE THREAD

**Issue by schthi3** [dr-leo/pandaSDMX#185]
As per the screenshot below, UNICEF doesn't seem to be listed as default provider (no designated file in: https://github.com/dr-leo/pandaSDMX/tree/master/pandasdmx/source). Can this be fixed?

![Screen Shot 2020-10-02 at 12 01 23 PM](https://user-images.githubusercontent.com/37111830/94950868-4e0b0680-04b1-11eb-85b3-aa87b5fde320.png)

**Comment by dr-leo** [comment]
This is intentional. The sources package only contains modules for providers that need special care such as Eurostat. Luckily, UNICEF seems to be working out of the box. Other providers such as United Nations or European central bank do not have a dedicated plug-in either. I would suggest to close this.

**Comment by schthi3** [comment]
Well noted, thanks for the feedback!
