### ISSUE TITLE
How to: convert dataframe to SDMX file

### ISSUE THREAD

**Issue by brockfanning** [dr-leo/pandaSDMX#187]
Hello! As I understand it, an SDMX writer was recently added to this library. (If I'm wrong about that, please feel free to close this!) I was wondering if it might be possible to get an example of how to use it to convert a relatively simple dataframe to an SDMX file. For example, suppose I'm starting with this dataframe:

TIME_DETAIL | UNIT_MEASURE | REF_AREA | OBS_VALUE
--- | --- | --- | ---
2016 | PT | 1 | 50
2017 | PT | 1 | 60
2016 | PT | 2 | 70
2017 | PT | 2 | 80
2016 | USD | 1 | 5000
2017 | USD | 1 | 6000
2016 | USD | 2 | 7000
2017 | USD | 2 | 8000

Assuming I also have access to a local DSD file that includes the corresponding dimensions/codes/attributes/etc, is it possible with this library to convert this into an SDMX file? If so, any code snippets or tips would be greatly appreciated!

**Comment by dr-leo** [comment]
Hi,

you are right: there is now a writer for SDMXML. But it is still
incomplete as it currently can output structure messages only, not
data messages or datasets. However, a more recent version of that
writer lives in a fork of pandaSDMX. It seems it does output data
sets. Hopefully, I'll find the time to merge this feature into
pandaSDMX soon. I didn't see the use case, but luckily you've proven
me wrong.

For now, I am working on fsspec support, i.e. the ability to work with
files in the cloud rather than just local. Adding the new SDMXML
writher should not be too much work though.

I should add that the SDMXML writer does not necessarily consume
pandas DataFrames, but a representation in terms of SDMX model
instances (see pandasdmx.model module). Hence, it would be interesting
to add a reader that takes a pandas DataFrame and converts it into the
model form.

Code contributions are welcome.

Leo

**Comment by dr-leo** [comment]
v1.2.0 has just been released. It includes the extended xml writer mentioned earlier. Re-open this issue as needed.

**Comment by brockfanning** [comment]
@dr-leo Thank you! I'm looking forward to trying it out. Your note about needing SDMX model instances (and not Pandas dataframes) is helpful. I wonder if you could point me to bare-bones example of "building" an SDMX model from scratch - if something like that exists. If not, any code links you could point me to, just to get started, would be helpful!

**Comment by dr-leo** [comment]
You can find example code in the GH repo under pandasdmx/tests. The
files test_model and writer/test_xml should be good starting-points.

The idea to convert a PD.DataFrame to an sdmxml file is interesting.

Good luck! - And I'd love to hear about the outcome.

**Comment by dr-leo** [comment]
Besides, yu could peruse test_model and the API docs for the model classes.

Start by instantiating a message.DataMessage, then a model.Dataset,
then add the Dataset to the message, add a message.Header, then
populate the Dataset with keys and observations iterating over the
dataframe. Shouldn't be a big deal.
