### ISSUE TITLE
IMF Error - Request

### ISSUE THREAD

**Issue by fcarpentey75012** [dr-leo/pandaSDMX#207]
Hello, 

I try to extract the data from IMF, but I have a strange error message : 

`XMLParseError: KeyError: 'TIME_FORMAT'`

Do you have any idea ? 

Thank you,

**Comment by dr-leo** [comment]
Hi,
I thought this error was fixed in version 1.0. So an update to the most recent version 1.4.2 might do the trick. This being said, and more importantly, the I am F no longer offers any data. You should be able to query meta-data, as you did, but if you still manage to query data, then I would be very surprised. The limitation of the IMF agency to meta-data is, by the way, documented in the package documentation.
Best regards
Leo

**Comment by fcarpentey75012** [comment]
Hello, thank you ! Yes in fact we can't extract the data. I have the same error from OECD

**Comment by fcarpentey75012** [comment]
`HTTPError: 400 Client Error: Semantic Error for url: https://stats.oecd.org/SDMX-JSON/dataflow/OECD/latest`

**Comment by dr-leo** [comment]
IMF does at best provide structural data, to my knowledge, but no data, at least not in SDMX 2.1. Please reopen if you have better news.
