### ISSUE TITLE
Pandas Writer failure on INSEE responses

### ISSUE THREAD

**Issue by alcibiade** [dr-leo/pandaSDMX#41]
I'm calling INSEE data series like this:

```python
import pandasdmx as pd
insee = pd.Request('INSEE')
resp_catABC = insee.data(resource_id='SERIES_BDM/001572432+001572433+001572434')
resp_catABC.write()
```

The outcome is:
```
jovyan@aba7a04d4412:~/work$ python3 test.py 
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    resp_catABC.write()
  File "/opt/conda/lib/python3.5/site-packages/pandasdmx/api.py", line 491, in write
    return self._writer.write(source=source, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/pandasdmx/writer/data2pandas.py", line 109, in write
    reverse_obs, fromfreq, parse_time))
  File "/opt/conda/lib/python3.5/site-packages/pandasdmx/writer/data2pandas.py", line 107, in <genexpr>
    series_list = list(s for s in self.iter_pd_series(
  File "/opt/conda/lib/python3.5/site-packages/pandasdmx/writer/data2pandas.py", line 184, in iter_pd_series
    elif freq_key in series.key._fields:
UnboundLocalError: local variable 'freq_key' referenced before assignment
```

I'm using Python 3.5.2 with pandasdmx 0.5.2 (in a jupyter/datascience-notebook docker container)

Am I doing something wrong here or is it a bug ?

I checked and the FREQ attribute is set to 'M' in the response XML, so the code in the data2pandas should work.

Thanks for the support !

**Comment by dr-leo** [comment]
Hi,


thanks for bringing this up. You are not the first to run into this
problem, see #39. I now consider it a bug.


I'll do my best to fix it. But it may take a while as I am drowning in
other stuff. Meanwhile, feel free to submit a PR if you feel like.


There is a work around: call write() with 'parse_time=False'. This
should yield a dataframe with a string index. Not ideal but still.


Happy new year!


Leo




Am 30.12.2016 um 21:50 schrieb Alcibiade:

**Comment by alcibiade** [comment]
Oh sorry, I didn't think about checking closed issues on the topic.

Thanks for the workaround !

Since you're busy, I'll try to work on a PR.

**Comment by dr-leo** [comment]
Hi,


as you may have seen, I've merged your PR, fixed some more issues and
churned out v0.6.


On your idea to simplify the code in lines 160-220 (roughly) iof the
data reader by putting series.kay and series.attrib into a single dict:


Admittedlythis part of the code is probably one of the ugliest within
pandaSDMX. So any simplification is welcome. That said, I was a bit
reluctant at first as you have to make the assumption that keys and
attributes do not have a common key, otherwise you would lose something
when populating the dict. Now I've changed my mind. It is a reasonable
assumption and even so: you want to have easy access to the FREQ value.
Note that both series.kay and series.attrib are namedtuple-like objects.


However, I haven't implemented your suggestion as I did not consider it
necessary and it wouldn't have improved on the behavior. I've even mesed
up your code at about line 200 as I wanted to raise a gentle error in a
particular situation. But I somehow missed the point. The conditions are
too complicated when reading them after a few months.


That said, I am now prepared for such a change if you want to make it.
There is still one bug. Actually, if you look at the code example in #39
provided by Otelo7, you see that OECD data sets may come without any
FREQ value, neither as key now attrib. In this case the writer still
crashes. The only work-around is to set pars_time=False.


I would be very happy if you could do a PR for this. I lack the time.
Will be offline for at least 8 days. But I am delighted anyway that v0.6
is out which irons out some serious bugs in 0.5.


Thanks again for your great contributions.


Leo

 



Am 03.01.2017 um 10:20 schrieb Alcibiade:

**Comment by alcibiade** [comment]
I tested on release 0.6 and confirm that this issue is now fixed.
