### ISSUE TITLE
ENH: return datasets into a xarray

### ISSUE THREAD

**Issue by KotZer** [dr-leo/pandaSDMX#45]
Returning multiindexed datasets into a [xarray](http://xarray.pydata.org/en/stable/) would be very useful

**Comment by dr-leo** [comment]
Sorry. This has been closed accidentally.

I see the use case. The heavy-weight option would be to ad a writer data2xarray. but this would imply some code duplication. Another more light-weight option would be to subclass the data2pandas writer, i.e. create the xarray from the PD DataFrame. But if we do this, wouldn't it not be acceptable for users to convert the df to xarray manually? You could also use odo for this.

Any thoughts or PR?

Leo

**Comment by dr-leo** [comment]
Please reopen if the Workaround described earlier does not work for you.

**Comment by dr-leo** [comment]
I reopen this issue because it seems there are use-cases for an xarray writer alongside the standard pandas writer.

However, I think an xarray writer should be developed separately from pandaSDMX. Ideally it would ship as a namespace package to be installed in pandasdmx.writer. Once it has matured, we might rethink adding it to pandaSDMX. I won't have time to contribute code to such writer in the foreseeable future. However, I would be happy to modify pandasdmx.api ensure seemless integration.

Any thoughts?

Leo

**Comment by dr-leo** [comment]
@khaeru: above comment FYI

**Comment by khaeru** [comment]
I don't have any experience with developing for or maintaining namespace packages. My only exposure is I've run into problems installing e.g. [basemap]() with [mpl_toolkits]() because the namespace system introduced incompatibilities between certain version combinations.

@dr-leo, if you have the time to convert pandaSDMX to a namespace package and want to do that, please go ahead. A simpler expedient would be for me to develop the version with an xarray writer in my own fork; you to specify what 'maturity' entails (e.g. test coverage, support for certain example data sets); and then me to only make a PR once this is satisfied (rather than bringing it to maturity within this main repo).

**Comment by dr-leo** [comment]
That's absolutely fine with me.

My main concern is not to stand in your way should you want to release
the forthcoming
xarray writer separately. But let's cross that Bridge when we come to it.

After a quick look at xarray, I am excited about the prospect of being
able to use it with pandaSDMX. Should you Need any Support, e.g., with
the pandaSDMX API, please feel free to contact me.

Leo

**Comment by dr-leo** [comment]
There has not been any Progress on this for quite some time. I am not fully convinced that this idea would fly as xarray requires uniformly typed data. SDMX does not guarantee this. Moreover, I think that any Pandas DataFrame may easily turned into an xarray object, but I haven't checked. 

Feel free to re-open if needed.

Leo
