### ISSUE TITLE
Error with concat=True

### ISSUE THREAD

**Issue by geoffwright240** [dr-leo/pandaSDMX#5]
get_data(...,concat=False) works but I am getting an error when I set get_data(...,concat=True). Not sure exactly what is going on here but error is below.

Python 2.7.8 (default, Dec 14 2014, 15:11:16) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin

In[2]: from pandasdmx import client
In[3]: client("Eurostat").get_data("namq_10_gdp",".CLV10_MEUR.SWDA.B1GQ.DE",concat=True)

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2883, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-666a295cca3b>", line 1, in <module>
    client("Eurostat").get_data("namq_10_gdp",".CLV10_MEUR.SWDA.B1GQ.DE",concat=True)
  File "/usr/local/lib/python2.7/site-packages/pandasdmx.py", line 507, in get_data
    [code_sets[k] for k in sorted_keys])
  File "/usr/local/lib/python2.7/site-packages/pandas/core/index.py", line 3576, in from_product
    labels = cartesian_product([c.codes for c in categoricals])
  File "/usr/local/lib/python2.7/site-packages/pandas/tools/util.py", line 33, in cartesian_product
    a[0] = 1
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by dr-leo** [comment]
While I don't know the precise cause of the error, I am aware of two
problems:

1. v0.1.2 uses from_product to generate the column index when
concatenating the series. This is wrong as there may or may not be any
series for every key. I have fixed this in
https://github.com/dr-leo/pandaSDMX/commit/aa4508c7ce58e1b742b5380101ce1b1fb96c88be

This replaces from_product by from_tuples as it should be.

2. Even if the returned series do not have the same frequency, concat
tries to coerce all series into a single dataframe. This may yield
unpreductible outcomes. This problem will be fixed in v0.2 (I hope) as
the information model will properly represent groups (i.e. subsets of
the series with group-specific metadata such as on frequency). Data
export should pay due regard to this.

Any help is much appreciated.
Am 02.01.2015 um 16:18 schrieb geoffwright240:

**Comment by dr-leo** [comment]
This is already fixed. Once the pandas writer will be brought to the front, this will no longer happen.
