### ISSUE TITLE
DSD response with UNSD agency

### ISSUE THREAD

**Issue by Charlescad** [dr-leo/pandaSDMX#66]
Hello dr-leo, 
I am trying to harvest some data from national accounts from the UNSD agency.
I tried the following code:
```
from pandasdmx import model, Request
unsd = Request('UNSD')
cat_response = unsd.categoryscheme()
print(cat_response.write().categoryscheme)
dsd_id = unsd.categoryscheme().dataflow.NA_MAIN.structure.id
dsd_response = unsd.datastructure(resource_id = dsd_id)
```
and I get the following error:
`Python\Anaconda3\lib\site-packages\requests\models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://data.un.org/WS/rest/datastructure/UNSD/NA_MAIN/latest/?references=all`

Is there anything I am doing wrong? 

Best,

Charlescad

`

**Comment by dr-leo** [comment]
Hi, I am currently off-line and cannot reproduce the error. My best guess is that the structure reference specifies a different agency ID look at the attributes of these trucks are reference to verify this. I would recommend not to request the data structure in the first place, Rhonda, my advice would be to request the data flow specifying the data flow ID. You should then receive a response containing the data structure, “lists etc. This does not work for all agencies though, as you can see from the example on the index page of the documentation. Let me know if this works for you. Regards, leo

**Comment by dr-leo** [comment]
I've doublechecked this and found that UNSD does not provide a dataflow with the ID you're looking for. Don't know why it Shows up in the categorizations.

>>> flows=un.dataflow()

Shows the dataflows that UNSD actually provides.

I recommend to use data from another agency such as IMF or OECD to retrieve data on national accounts.

**Comment by Charlescad** [comment]
Hi,
Sorry for the last answer. Here is my code:


from pandasdmx import model, Request
# List of agencies
print(Request.list_agencies())
# UNSD Agency
unsd = Request('UNSD')
cat_response = unsd.categoryscheme()
print(cat_response.write().dataflow) # dataflows into category schemes

I see that there is a NA_MAIN into the category scheme NATIONAL_ACCOUNTS
and i try to get data from there:

This one works:

print('Number of series:', unsd.preview_data('NA_MAIN', count = True, total
= True))
series_keys = unsd.series_keys('NA_MAIN',cache = True)
print(list(series_keys))

From there, I suspect that there is a DataStructure NA_MAIN  and I want to
explore this. For that, I want to use dsd.
# Series keys on NA_MAIN
dsd_id = unsd.categoryscheme().dataflow.NA_MAIN.structure.id
print(dsd_id)
refs = dict(references = 'all')
print(unsd.categoryscheme().url) # URL category schemes
dsd_response = unsd.datastructure(resource_id = dsd_id, params = refs)


While it works on another dataset that I can see not through the
categoryscheme but in dataflows:

print(unsd.dataflow().write()) # dataflows not necessarly into category
schemes
# Series keys on another dataset
dsd_id = unsd.categoryscheme().dataflow['DF_UNDATA_COUNTRYDATA'].
structure.id
print(dsd_id)
refs = dict(references = 'all')
dsd_response = unsd.datastructure(resource_id = dsd_id, params = refs)
print(dsd_response.write())

Is that right? Sorry I am a new python user as well as a new pandaSDMX
user.

Thank you very much,

Charles.

**Comment by dr-leo** [comment]
Thanks. I will try to reproduce this. But it may take some time (I
have day-job and Kids).

Note that the preview_data method does not download the DSD, but
attempts to download an empty dataset with all valid series keys. You
can see tzis by inspecting the Cache or memcache dict attached to the
Request instance. Perhaps this already answers your question. - It
would be an error if an agency offered a dataflow with no DSD. But do
a dir() on the .structure reference attached to the dataflow. And you
can see the agency_ID of the agency providing that DSD. In v0.8.2 some
of the Ref Attributes were Buggy. This is fixed in the dev branch on
github.


On a General note, it would be extremely helpful if you could send
Code examples with Outputs. This would save me (or any other reader) a
lot of time. To do this, you may wish to use the excellent and very
popular browser-based Jupyter Notebook or the IPython console if you
prefer. As a Python novice you may want to consider using Jupyter
anyway. It may Change your life.

**Comment by Charlescad** [comment]
Hi again,
Thank you so much this is already super nice to verify that!
Here are the results in a more readable fashion created via Jupyter
Notebook.
In the meantime, I checked dir() on the structure and the agency_id: this
is ESTAT providing this dataset!
At this step, I think that we can say you have resolved my issue,
Thank you so much,

Best,

Charles.
