### ISSUE TITLE
Working with custom / unlisted agency

### ISSUE THREAD

**Issue by alexandersimoes** [dr-leo/pandaSDMX#68]
Hello!

I wasn't quite sure where to post this and got a bit confused looking through all the docs and reading through the source. Basically I'm trying to use this site as a source: http://andmebaas.stat.ee/. And more specifically this table: http://andmebaas.stat.ee/Index.aspx?DataSetCode=VK10_3&lang=en.

Here is what I've tried but keep getting stuck:
```
from pandasdmx import *
r = Request()
ds = r.get(url="http://andmebaas.stat.ee/restsdmx/sdmx.ashx/GetDataStructure/VK10_3", resource_type='datastructure')
ds.dimensions
```

To which I get:
```
AttributeError: 'StructureMessage' object has no attribute 'dimensions'
```

Any help would be super appreciated, thanks!

**Comment by dr-leo** [comment]
Hi, thanks for raising this issue. Estonians statistics should definitely be added as an officially supported agency in the next release. Given that you are trying to download the data set, you should said the resource type to data rather than data structure. Please let me know if this works for you.
Regards
Leo

**Comment by alexandersimoes** [comment]
Hmm, still doesn't seem to work. I also tried using an endpoing that I knew returned data and not just structure:

```
eeresp = r.get(url="http://andmebaas.stat.ee/restsdmx/sdmx.ashx/GetData/VK10_3/TRD_VAL.EXP..TOTAL.M/all?startTime=2018-01&endTime=2018-08&dimensionAtObservation=allDimensions", resource_type='data') 
```

But receive the following error:

```
ValueError: Unsupported root tag: {http://www.SDMX.org/resources/SDMXML/schemas/v2_0/message}MessageGroup
```

It would be amazing to add Estonian statistics as another supported agency here, I'm also happy to help w/ a PR just not sure where to get started. Thanks!

**Comment by dr-leo** [comment]
So I reran your code. The xml file returned by the service is in the old SDMX 2.0 format. You can see this by running:

>>> ds.msg._elem

So either Estonian stats has another end point supporting SDMX 2.1, or pandaSDMX will never support it.

**Comment by khaeru** [comment]
Hi @alexandersimoes—just to be clear, the SDMX format for XML and REST web services changed a _lot_ between 2.0 and 2.1. It's already been a lot of work to (almost) fully support the 2.1 version, and since the major web services are all on 2.1, it's not currently a target to support 2.0. So I'm going to close this issue.

If you wanted to put (probably a lot of) time into developing 2.0 support, you could start by forking the repo; you'd need to create both a parallel version to pandasdmx.reader.sdmxml.Reader that handles 2.0-format messages, as well as a parallel version of pandasdmx.api.Request that constructs 2.0-format URLs.

But I think it might be a better use of time to beseech the Estonian statistics agency to upgrade their web service to 2.1!

PS. we currently have a HOWTO for unlisted data sources: https://pandasdmx.readthedocs.io/en/latest/howto.html#access-other-sdmx-data-providers —it does say "2.1" but maybe that's not super clear that 2.0 services are still around and are not supported. I'd also welcome a small PR that updates the docs to make that explicit and inform people.
